wget -O ~/THÉO/SummaryMR/Vitamin-D.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/100021_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Fluid-intelligence-score.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/20016_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Body-mass-index-BMI.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/21001_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Weight.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/21002_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Whole-body-fat-mass.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/23100_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Platelet-count.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30080_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Neutrophill-count.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30140_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Forced-vital-capacity-FVC.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/3062_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Heel-bone-mineral-density-BMD.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/3148_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Hand-grip-strength-right.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/47_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Standing-height.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/50_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Albumin-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30600_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/Creatinine-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30700_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/Alkaline-phosphatase-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30610_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/Alanine-aminotransferase-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30620_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/Aspartate-aminotransferase-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30650_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/C-reactive-protein-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30710_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/Cystatin-C-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30720_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/Gamma-glutamyltransferase-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30730_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/Glycated-haemoglobin-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30750_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/IGF-1-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30770_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/SHBG-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30830_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/Triglycerides-quantile.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30870_irnt.gwas.imputed_v3.both_sexes.varorder.tsv.bgz
wget -O ~/THÉO/SummaryMR/Age-when-periods-started-menarche.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/2714.gwas.imputed_v3.both_sexes.tsv.bgz
wget -O ~/THÉO/SummaryMR/Relative-age-of-first-facial-hair.tsv.bgz https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/2375.gwas.imputed_v3.both_sexes.tsv.bgz

